### ISSUE TITLE
Use existing crates

### ISSUE THREAD

**Issue by MathiasKoch** [rust-embedded-community/embedded-nal#1]
This looks great for getting us started!

Maybe we should consider using the existing https://github.com/dunmatt/no-std-net for IPAddress and SocketAddress, as that is essentially the `std::net` without the `std` part.

Perhaps it would even make sense eventually to merge the two..

**Comment by thejpster** [comment]
That looks more complete that what I have, so happy to take a PR that deletes my IP address types,  adds a dependency on https://crates.io/crates/no-std-net and just re-exports their types.
