### ISSUE TITLE
Proposal: embedded-nal-async

### ISSUE THREAD

**Issue by lulf** [rust-embedded-community/embedded-nal#65]
I'd like to propose following a similar path to embedded-hal-async and add an embedded-nal-async crate within this repo. I have been maintaining some async traits for TCP[^1] and DNS[^2] that I feel would be a good fit for this crate (assuming some adjustments to fit the existing embedded-nal conventions). I'm available to take on that effort.

[^1]: https://github.com/drogue-iot/drogue-device/blob/main/device/src/traits/tcp.rs
[^2]: https://github.com/drogue-iot/drogue-device/blob/main/device/src/traits/dns.rs

**Comment by ryan-summers** [comment]
I see no reason not to support that here :) It indeed matches the approach of embedded-hal-async.

**Comment by MathiasKoch** [comment]
I think that makes great sense! :+1:
