### ISSUE TITLE
Support trait for DNS

### ISSUE THREAD

**Issue by MathiasKoch** [rust-embedded-community/embedded-nal#8]
Would it make sense to add a support trait for DNS lookups?

Somthing along the lines of
```rust
pub trait Dns {
    /// The type returned when we have an error
    type Error: core::fmt::Debug;

    fn resolve(&self, hostname: &str) -> Result<IpAddr, Self::Error>;
}
```

**Comment by thejpster** [comment]
This is a good idea! But, perhaps we also need to handle:

* Letting the user choose which record (A, AAAA, TXT, etc)
* Iterating through a set of results (you might get several and need to try them in turn)

I can't recall what the Berkeley socket API looks like, but it's probably awful. How do things like lwip do this?

**Comment by MathiasKoch** [comment]
Thats a very good point! I forgot about DNS being a bit more than just a single resolve. 
I will peek at how lwip does this! And probably at the Berkeley socket API as well, just to check.

Will return shortly

**Comment by MathiasKoch** [comment]
It seems like the Berkeley socket API is pretty much just `gethostbyname` and `gethostbyaddr`, when it comes to DNS?

They do return a struct with a list of addresses though (as you mentioned), on the form:
```
struct hostent {
    char  *h_name;            /* official name of host */
    char **h_aliases;         /* alias list */
    int    h_addrtype;        /* host address type */
    int    h_length;          /* length of address */
    char **h_addr_list;       /* list of addresses */
}
```

So we should probably work that into the trait

**Comment by thejpster** [comment]
Do we want to limit ourselves to platforms that can create an `alloc:Vec`, or should we take an `&mut [DnsResult]` and return a sub-slice of that?

**Comment by MathiasKoch** [comment]
I would be a bit sad if we limited it to alloc applications.. I think either the `&mut [DnsResult]` version, or go with one of the heapless alternatives to alloc

**Comment by MathiasKoch** [comment]
I am not sure `gethostbyaddr` makes any kind of sense in an embedded context?

So the resulting trait would look very much like (depending on what we go for wrt slice/vec)
```rust
pub trait Dns {
    /// The type returned when we have an error
    type Error: core::fmt::Debug;

    fn gethostbyaddr(&self, hostname: &str) -> Result<Vec<IpAddr>, Self::Error>;
}
```

Where the `Vec<IpAddr>` might be some kind of `DnsResult` instead, though i am not sure that makes sense in an embedded context either? What would it contain other than address?

**Comment by thejpster** [comment]
TXT records, IPv4 A record, IPv6 AAAA record, CNAME, MX, DKIM, SPF - there's lots of DNS records.

**Comment by MathiasKoch** [comment]
Yeah, i get that. But neither the Berkeley API, nor rust std::net seems to take that into account? Not in requests, and not in the response.

https://doc.rust-lang.org/1.4.0/std/net/index.html

Nor does what seems to be rust wrapper around the unix interface used for DNS:
https://docs.rs/dns-lookup/1.0.1/dns_lookup/

If there is currently no, or very few, implementations even supporting this, i am not convinced it makes much sense to spend a lot of time on how to incorporate the options into a trait like this. Rather i think someone should open a proposal PR when the feature is actually needed? Given that most implementations of said trait, would probably only be able to lookup A records atm.
