### ISSUE TITLE
New release of `embedded-nal`

### ISSUE THREAD

**Issue by elpiel** [rust-embedded-community/embedded-nal#84]
It seems that there is small discrepancy between the embedded-nal & embedded-nal-async crates which causes some issues for me. embedded-nal current release has dependency on `no-std-net 0.5` but `-async` has on `0.6`.

Even though `no-std-net` hasn't had any release in a while and is not actively maintained, there is a small difference and with the new support for `ip_in_core` it seems fitting to make a new release of `embedded-nal`.

**Comment by ryan-summers** [comment]
I'm not sure I fully understand what the issue you're referring to is? You mention that both use `no-std-net` at 0.5, but is it that one is 0,4 and the other is 0.5?

**Comment by ryan-summers** [comment]
I'm planning on doing some TCP updates here shortly and would like to cut a release soon, so I can incorporate this fix in :)

**Comment by elpiel** [comment]
@ryan-summers yes, I had a typo in my issue sorry about that.
So yes, because one version is different than the other I was getting issues with my dependencies.

Quick note that I reached out to the `no-std-net` maintainer and we're discussing the additional of new maintainer(s) to cut out a new release of the crate too.
